mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  username: YOURUSERNAME
  password: YOURPASSWORD

light:
  - platform: mqtt_json
    name: "Porch Strip"
    state_topic: "led/porch"
    command_topic: "led/porch/set"
    effect: true
    effect_list:
      - solid
      - twinkle
      - cylon bounce
      - fire
      - fade in out
      - strobe
      - theater chase
      - rainbow cycle
      - color wipe
      - running lights
      - snow sparkle
      - sparkle
      - twinkle random
    brightness: true
    flash: true
    rgb: true
    white_value: true
    optimistic: false
    qos: 0

input_number:
  porch_animation_speed:
    name: Porch Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation: 
  - alias: "Porch Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_slider.porch_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "led/porch/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
